apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: dj-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: sbhusal123/django-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-conf
          volumeMounts:
            - name:  media-storage
              mountPath:  /app/media
            - name:  static-storage
              mountPath:  /app/static
      volumes:
        - name:  media-storage
          persistentVolumeClaim:
            claimName: media-pvc
        - name: static-storage
          persistentVolumeClaim:
           claimName: static-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  namespace: dj-kubernetes
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
